version: 2.1
jobs:
    build:
        working_directory: ~/chronos
        docker:
            - image: circleci/node
            - image: mongo
            - image: redis
            - image: djfarrelly/maildev
        steps:
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: test
                command: npm test