name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    services:
      mongo:
        image: mongo:3.6.14
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
      mail:
        image: djfarrelly/maildev
        ports:
          - 1080:80
          - 1025:25

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Authenticating to Team Berry's GitHub Registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_KEY }}" >> ~/.npmrc
    - name: Install Dependencies
      run: npm install
    - name: Setup Auth Keys
      run: mkdir -p certs; cd certs; openssl genrsa -out auth 2048; openssl rsa -in auth -pubout -outform PEM -out auth.pub;
    - name: Lint check
      run: npm run lint:check
    - name: Run Tests
      run: npm run test
      env:
        CI: "true"

  deploy:

    runs-on: ubuntu-18.04

    if: github.workflow.test

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Auth Keys
        run: mkdir -p certs; cd certs; openssl genrsa -out auth 2048; openssl rsa -in auth -pubout -outform PEM -out auth.pub;
      - name: Install Dependencies & Build App
        run: |
          npm ci
          npm run build
      - name: Clean dist folder
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: rm -rf ${{ secrets.LOCATION }}/dist/*
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy files
        uses: horochx/deploy-via-scp@v1.0.1
        with:
          local: dist package.json npm-shrinkwrap.json processes.json
          remote: ${{ secrets.LOCATION }}
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Dependencies & Restart Server
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          command: |
            npm ci
            npm restart
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}



