name: Test

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build:
    name: Check Tests & Lint Rules
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    services:
      mongo:
        image: mongo:3.6.14
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
      mail:
        image: djfarrelly/maildev
        ports:
          - 1080:80
          - 1025:25
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticate to Team Berry's GitHub Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.REGISTRY_KEY }}" >> ~/.npmrc
      - name: Install Dependencies
        run: npm install
      - name: Setup Auth Keys
        run: mkdir -p certs; cd certs; openssl genrsa -out auth 2048; openssl rsa -in auth -pubout -outform PEM -out auth.pub;
      - name: Lint check
        run: npm run lint:check
      - name: Run Tests
        run: export YOUTUBE_API_KEY=${{ secrets.TEST_YOUTUBE_API_KEY }} ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }} && npm run coverage
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
